### PR TITLE
Fix duplicated items, rework MainWindow memory-management

### LINKED ISSUE #312: Duplicated menu entries after properties changed
This seems a bug caused by #256. After changing some properties (for example uses a smaller font size or vice versa), there are duplicate actions in the menu.
duplicated_actions

I guess ```rebuildActions``` does not clear previous actions completely. @pas2k Could you have a look?

### PR DESCRIPTION
**Pull request by pas2k**
These changes fix the memory management inside MainWindow related to setting changes.

QActions and QMenus allocated with `new`, were bound to the window itself, so those weren't cleaned up when replaced. The issue can be reproduced by opening Settings and repeatedly pressing Apply while monitoring QTerminal memory consumption.

The leaks aren't visible on Valgrind since the leaked objects are properly deleted when the window closes, so Massif was used for debugging.

The fix is twofold:
- Instead of binding all constructed QObjects to the window itself, a proxy object `settingOwner` is used. It's destroyed and re-created on setting changes, so all child objects follow.
- The nested menus aren't re-created on Setting changes. The `settingOwner` trick would have reduced the changeset, reworking nested menus dynamically result in `DBusMenuExporterDBus` warnings for some reason. 

This also fixes #312

### CODE REVIEW

File: src/mainwindow.cpp [hunk 1]
```diff
@@ -111,16 +119,14 @@ MainWindow::MainWindow(const QString& work_dir,
 
 void MainWindow::rebuildActions()
 {
-    QMap< QString, QAction * > oldActions(actions);
+    // Delete all setting-related QObjects
+    delete settingOwner;
+    settingOwner = new QWidget(this);
```
Comment (yan12125) [inline src/mainwindow.cpp]: Is ```QWidget``` necessary? I guess ```QObject``` is enough.

File: src/mainwindow.h [hunk 2]
```diff
@@ -48,6 +48,10 @@ class MainWindow : public QMainWindow, private Ui::mainWindow
     QActionGroup *tabPosition, *scrollBarPosition, *keyboardCursorShape;
     QMenu *tabPosMenu, *scrollPosMenu, *keyboardCursorShapeMenu;
 
+    QWidget *settingOwner;
```
Comment (yan12125) [inline src/mainwindow.h]: Could you add some comments for this object? It's not intuitive from the name.

File: src/mainwindow.cpp (hunk 1 above)
Comment (pas2k) [inline src/mainwindow.cpp]: If menus are to be re-parented, then yes, QWidget is necessary. But since menus are not re-parented due to DBusMenuExporterDBus warnings, it's not that necessary. Can be useful in future for other setting-related QWidgets, so I'd say it's justified.

**Comment by agaida** [comment]
@pas2k - would you be so kind and rebase - GTM when rebased.

**Comment by pas2k** [comment]
@agaida Done -- and ready to rebase again once some other commits are merged.

**Comment by agaida** [comment]
hmm - the patch applies, the package build and install fine - there is only one problem, i can't click on File and Action any longer reliable - both menu entries react not reliable or not on mouseclicks. all other top level menu entries do. The keyboard shortcuts work just fine.

**Comment by agaida** [comment]
@pas2k - sorry, could you rebase again, really not my day

**Comment by pas2k** [comment]
@agaida No problem, done. As for File/Action, I'm not seeing any difference in functionality or responsiveness compared to master. I'm on Ubuntu 17.04, recently updated from 16.10 (where this was also fine, I use qterminal on daily basis), qt is stock.

**Comment by agaida** [comment]
good, will test it again - i was a little bit surprised too

**Comment by agaida** [comment]
@pas2k - ok, it is weird - but i made a little video: https://youtu.be/9b22pfd-xZs

**Comment by agaida** [comment]
ok, next information - the menu behave ok after i opened preferences and hit ok or apply - cancel is not sufficient.

**Comment by pas2k** [comment]
@agaida Thanks for the video! I was able to reproduce the issue on non-ubuntu VM with no menubar integration. Turns out the *invisible parent QWidget* was blocking the menu. Doh! Fixed by setting its geometry to 0 (to avoid possibly hiding children with hide()). Should be fine now.

**Comment by agaida** [comment]
Cool, thanks.

**Comment by agaida** [comment]
GTM
